# Generated by Django 4.2.2 on 2023-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
