# Generated by Django 4.2.2 on 2023-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='eventdate',
            field=models.DateField(null=True),
        ),
    ]
