# Generated by Django 4.2.2 on 2023-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_applications', '0003_job_application_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='job_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
