# Generated by Django 4.2.2 on 2023-06-06 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Technical", "Technical"),
                            ("Marketing", "Marketing"),
                            ("Education", "Education"),
                            ("Govt_Job", "Govt_job"),
                        ],
                        max_length=100,
                    ),
                ),
                ("resume", models.FileField(upload_to="documents/")),
                ("resume_name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
