# Generated by Django 4.2.2 on 2023-06-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=2000)),
                ("company_name", models.CharField(max_length=100)),
                ("experience", models.IntegerField()),
                ("job_id", models.CharField(max_length=100, null=True)),
                ("job_url", models.CharField(max_length=100, null=True)),
                ("location", models.CharField(max_length=200, null=True)),
                ("skills_required", models.CharField(max_length=1000, null=True)),
                ("publishing_time", models.DateTimeField(auto_now=True)),
                ("last_date_of_application", models.DateField()),
                ("test_date", models.DateField(null=True)),
                ("interview_date", models.DateField(null=True)),
            ],
        ),
    ]
