# Generated by Django 4.2.2 on 2023-06-21 13:46

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('head_quarters', models.CharField(max_length=20)),
                ('openings', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('company_name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('job_id', models.CharField(max_length=100, null=True)),
                ('job_url', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('skills_required', models.CharField(max_length=1000, null=True)),
                ('publishing_time', models.DateTimeField(auto_now=True)),
                ('last_date_of_application', models.DateField()),
                ('test_date', models.DateField(null=True)),
                ('interview_date', models.DateField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.company')),
            ],
        ),
    ]
