# Generated by Django 4.2.2 on 2023-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Jobs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="last_date_of_application",
        ),
    ]
