# Generated by Django 3.2.19 on 2023-06-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_applications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('val1', 'Applied'), ('val2', 'Under Consideration'), ('val3', 'Interviewed'), ('val4', 'declined')], max_length=20)),
                ('job_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
